### ISSUE TITLE
Language tags in KGCL

### ISSUE THREAD

**Issue by ckindermann** [cmungall/knowledge-graph-change-language#13]
How should language tags be supported explicitly by KGCL?

I am assuming statements such as `"rename UBERON:0002398 from 'manus' to 'hand'"` should preserve available language tags. But what about inputs such as `"rename UBERON:0002398 from 'manus@en' to 'hand@en'"`? Should `'manus@en'` be interpreted as `"manus@en"` or `"manus"@en`? 

This ambiguity could be avoided by making language tags explicit in KGCL, e.g. `"rename UBERON:0002398 from 'manus'@en to 'hand'@en"`. In this case, we'd need to extend the KGCL data model to hold information about language tags.

**Comment by cmungall** [comment]
See #12. Here the language tag is a separate field rather than using any string syntax

and yes sensible defaults should apply. In the context object could have configurations such as default language, default type for text annotations, preserve language on rename, etc
