### ISSUE TITLE
Dependencies from imports are not generated correctly in Python Dataclasses

### ISSUE THREAD

**Issue by ckindermann** [cmungall/knowledge-graph-change-language#15]
Running `pipenv run gen-py-classes kgcl.yaml > kgcl.py` generates the desired `kgcl.py` file.
However, import dependencies from the modules `ontology_model` and `prov` are not generated correctly.
For example, instead of `about_edge: Optional[Union[dict, Edge]] = None` I find `about_edge: Optional[Union[dict, "Edge"]] = None`.

**Comment by ckindermann** [comment]
Running `pipenv run gen-py-classes --no-mergeimports kgcl.yaml > kgcl.p` resolves the dependencies correctly.

**Comment by cmungall** [comment]
It looks like merging the imports resolved the issue - but it's not clear there was an issue, it's valid to declare the python type as a string, this is common practice for forward referencing
