### ISSUE TITLE
Implement NodeObsoletionWithDirectReplacement

### ISSUE THREAD

**Issue by cmungall** [cmungall/knowledge-graph-change-language#23]
required for mondo, will assign to @joeflack4

**Comment by joeflack4** [comment]
_Chris said:_
> Standalone python module. uses rdflib. For this one task. 
> 
> got to cut out a node, rewire it, hop over thing that is gone. worry about logic. do it incrementally; so order dependent. but lots of edge cases. what about other kinds of relationships? what happens if we have some of those pointing to that.
> 
> Would be ideal to do first in Python and can reimplement after in KGCL.

## Questions
1. What are my inputs?
2. What is output format? .ttl?
3. Can I get a more clear explanation of what is supposed to be done?

**Comment by joeflack4** [comment]
Closing this issue as we determined that this would involve too much manual curator effort to make automating any part of this worthwhile.
